#!/bin/bash

set -eou pipefail -x

# jq is required to read data file.
test -x $(command -v jq)

export CFGFILE="build.cfg"
export DISTRO=$(source /etc/os-release; echo $ID)
export DISTRO_VERSION=$(source /etc/os-release; echo $VERSION_ID)
# Strip the minor version since the script is designed to work on major versions.
export DISTRO_COMBO="${DISTRO}${DISTRO_VERSION%.*}"
export ROOT="/opt/errbot"
export VENVDIR="${ROOT}/venv"
export BUILD_ROOT=$(pwd)/$(jq -r '._common.build_dir' "${CFGFILE}")
export PKGS=( $(jq -r ".${DISTRO_COMBO}.archive_deps[]" "${CFGFILE}") )
export PYBIN="/usr/bin/$(jq -r ".${DISTRO_COMBO}.pybin" "${CFGFILE}")"
export ERR_STACKSTORM_VERSION=$(jq -r '._common.version' "${CFGFILE}")
export ERRBOT_VERSION=$(jq -r '._common.errbot.version' "${CFGFILE}")

# Package contains the following software projects and their respective licence.
#
# errbot                      GPL3
# err-backend-discord         GPL3
# err-backend-slackv3         GPL3
# err-backend-botframework    MIT License
# err-backend-mattermost      GPL3
#
# err-stackstorm              Apache 2.0
#
# The build process is the following:
#  1. Acquire the source code and install build time dependencies
#  2. Create virtualenv and install dependencies.
#  3. Prune virtualenv of git metadata and python compiled bytecode.
#  4. Create tar.gz snapshot of virtualenv for OS/architecture
#  5. Run package build processusing latest tar.gz
#  6. Update repository with package.

# References
#
# https://gist.github.com/fernandoaleman/1377211/d78d13bd8f134e7d9b9bc3da5895c859d7cbf294
# https://gist.githubusercontent.com/fernandoaleman/1377169/raw/3e841ca1a887dd21f3fcb35a3e74b0cc2fc4977b/create-repo-metadata.sh
function title
{
    echo -e "\033[37;1;206;44;1;57m${1}\033[0m"
}
function rocky8_install
{
    dnf install -y "${PKGS[@]}"
}
function rocky9_install
{
    dnf install -y "${PKGS[@]}"
}
function ubuntu20_install
{
    apt install "${PKGS[@]}"
}
function ubuntu22_install
{
    apt install "${PKGS[@]}"
}
function ubuntu24_install
{
    apt install "${PKGS[@]}"
}
function debian11_install
{
    apt install "${PKGS[@]}"
}
function debian12_install
{
    apt install "${PKGS[@]}"
}

function install_system_requirements
{
    title "INSTALL SYSTEM REQUIREMENTS"
    "${DISTRO_COMBO}_install"
}

function create_virtual_environment
{
    title "CREATE VIRTUAL ENVIRONMENT ${VENVDIR}"
    "${PYBIN}" -m venv "${VENVDIR}"
    cd "${ROOT}"
    mkdir -p ./{plugins,backends,data}
}

function fetch_archives
{
    title "DOWNLOAD ARCHIVES to ${BUILD_DIR}"
    export BACKENDS=("err-backend-discord" "err-backend-slackv3" "err-backend-gitter" "err-backend-mattermost" "err-backend-botframework")

    mkdir "${BUILD_DIR}/backends"
    cd "${BUILD_DIR}"
    wget "https://github.com/errbotio/err-backend-discord/archive/refs/tags/v4.0.0.tar.gz" -O "backends/err-backend-discord-v4.0.0.tar.gz"
    wget "https://github.com/errbotio/err-backend-slackv3/archive/refs/tags/v0.2.1.tar.gz" -O "backends/err-backend-slackv3-v0.2.1.tar.gz"
    wget "https://github.com/errbotio/err-backend-mattermost/archive/refs/tags/3.0.0.tar.gz" -O "backends/err-backend-mattermost-v3.0.0.tar.gz"
    wget "https://github.com/nzlosh/err-backend-gitter/archive/refs/tags/v0.1.0.tar.gz" -O "backends/err-backend-gitter-v0.1.0.tar.gz"
    wget "https://github.com/nzlosh/err-backend-botframework/archive/refs/tags/v0.1.0.tar.gz" -O "backends/err-backend-botframework-v0.1.0.tar.gz"

    mkdir "${BUILD_DIR}/plugins"
    export PLUGINS=("err-stackstorm")
    wget "https://github.com/nzlosh/err-stackstorm/archive/refs/tags/v${ERR_STACKSTORM_VERSION}.tar.gz" -O "plugins/err-stackstorm-v${ERR_STACKSTORM_VERSION}.tar.gz"
}

function install_extensions
{
    title "INSTALL ERRBOT EXTENSIONS to ${BUILD_DIR}"
    for location in backends plugins
    do
        # extract
        for targz in "${BUILD_DIR}/${location}"/*.tar.gz
        do
            tar xf "$targz" -C "${ROOT}/${location}"
        done
        # install dependencies
        for proj in "${ROOT}/${location}"/*
        do
            # Install from pyproject
            if [[ -f "${proj}/pyproject.toml" ]]; then
                pip install "${proj}"
            elif [[ -f "${proj}/requirements.txt" ]]; then
                # Install from requirements
                pip install -r "${proj}/requirements.txt"
            fi
        done
    done

    for location in "${ROOT}/backends"
    do
        cd "${location}"
        for backend in "${BACKENDS[@]}"
        do
            # Move archive directory names to correct errbot names.
            mv -f ./*"${backend}"* "$backend"
        done
    done

    for location in "$ROOT/plugins"
    do
        cd "$location"
        for plugin in "${PLUGINS[@]}"
        do
            mv -f ./*"${plugin}"* "$plugin"
        done
    done
}

function prune_installation
{
    title "PRUNE INSTALLATION"
    # Remove python cache files and hidden files.
    find "${VENVDIR}" -iname '*.pyc' -delete
    # Remove unrequired directories
    for dir in '__pycache__' ".github" "docs" "tests"
    do
        for x in $(find "${VENVDIR}" -iname "$dir" -type d)
        do
            rm -rf "${x}"
        done
    done
    # Remove non-core code from err-stackstorm
    for excess in contrib docs tests
    do
        rm -rf "$ROOT/plugins/err-stackstorm/${excess}"
    done

}



function install_errbot
{
    title "INSTALL ERRBOT ($(${VENVDIR}/bin/pip --version))"
    source "${VENVDIR}/bin/activate"
    pip install --upgrade pip setuptools
    # Use tmp dir to download and build errbot/plugins.
    TMP_DIR="${BUILD_ROOT}"
    mkdir -p "${TMP_DIR}"
    export BUILD_DIR=$(mktemp -d "${TMP_DIR}"/build.XXXXXX)
    cd "$BUILD_DIR"
    wget "https://github.com/errbotio/errbot/archive/refs/tags/${ERRBOT_VERSION}.tar.gz" -O errbot-v${ERRBOT_VERSION}.tar.gz
    tar xf errbot-v${ERRBOT_VERSION}.tar.gz
    cd errbot-${ERRBOT_VERSION}
    pip install .[IRC,XMPP,telegram]
    fetch_archives
    install_extensions
    prune_installation
}


function build_archive
{
    install_system_requirements
    create_virtual_environment
    install_errbot
    tar czf "/opt/err-stackstorm_${ERR_STACKSTORM_VERSION}_${DISTRO_COMBO}_x86_64.tar.gz" "${ROOT}"
}

function build_system_package
{
    title "BUILD SYSTEM PACKAGE FROM ARCHIVE in ${BUILD_DIR}"
    WORKDIR=$(dirname ${BUILD_ROOT})
    cd "${WORKDIR}"
    ${PYBIN} -m venv "${BUILD_DIR}/venv"
    source "${BUILD_DIR}/venv/bin/activate"
    pip install -r "${WORKDIR}/requirements.txt"
    $(basename ${PYBIN}) ./build
    # Remove temp build dir
    rm -rf "${BUILD_DIR}"
}

test -x $PYBIN

build_archive
build_system_package
