#!/bin/bash

set -e

VERB="$1"
VERSION="$2"

E_BAD_VERB=1
E_BAD_VERSION=2
E_BAD_ARGS=3

function check_version
{
    VERSION="$1"
    if [[ -z "$VERSION" ]]; then
        echo "Warning! $0 $VERB called without providing a package version."
        #exit $E_BAD_VERSION
    fi
}

case "$VERB" in
    install)
        if [[ -z "$VERSION" ]]; then
            echo "$0 $VERB"
        else
            echo "$0 $VERB old-version: $VERSION"
        fi
    ;;
    upgrade)
        check_version "$VERSION"
        echo "$0 $VERB old-version: $VERSION"
    ;;
    abort-upgrade)
        check_version "$VERSION"
        echo "$0 $VERB old-version: $VERSION"
    ;;
    *)
        echo "$0 called with unexpected package action '$VERB'"
        exit $E_BAD_VERB
    ;;
esac
