name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install requirements
        run: |
          make -s setup

      - name: Linting
        run: |
          make -s auto_format
          make -s lint_test

      - name: Unit Tests
        run: |
          make -s unit_test

      - name: Security Scan
        run: |
          make -s security_scan

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          make setup

      - name: Build pypi
        run: |
          echo TO DO - make pypi package.

      - name: Build documentaiton
        run: |
          echo TO DO - make readthedocs documentation.
